/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.UtilDOM;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import org.w3c.dom.Attr;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NamedNodeMap;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

/**
 *
 * @author usumaniana
 */
public class GUI extends javax.swing.JFrame {

    DefaultListModel dlmCurso;
    DefaultListModel dlmGrupo;
    DefaultListModel dlmMateria;
    
    
    
    public GUI() {
        initComponents();
        dlmCurso = new DefaultListModel();
        dlmGrupo = new DefaultListModel();
        dlmMateria = new DefaultListModel();
        
        lst_cursos.setModel(dlmCurso);
        lst_grupos.setModel(dlmGrupo);
        lst_materias.setModel(dlmMateria);
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_cursos = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_grupos = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lst_materias = new javax.swing.JList<>();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        mn_importar = new javax.swing.JMenuItem();
        mn_restore = new javax.swing.JMenuItem();
        mn_save = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lst_cursos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "CURSOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        lst_cursos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lst_cursos);

        lst_grupos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "GRUPOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        lst_grupos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lst_grupos);

        lst_materias.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "MATERIAS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        lst_materias.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(lst_materias);

        jMenu3.setText("Archivo");

        mn_importar.setText("Importar");
        jMenu3.add(mn_importar);

        mn_restore.setText("Recuperar");
        jMenu3.add(mn_restore);

        mn_save.setText("Guardar");
        jMenu3.add(mn_save);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        UtilDOM u = new UtilDOM();
        Document doc = u.xml2dom("ExportacionGRUPOS-MATERIAS.xml");
        doc.normalize();
        Element raiz = doc.getDocumentElement();
        NodeList listas =  raiz.getElementsByTagName("listasal");
        
        List<Node> grupos = new ArrayList();
        
        for (int i = 0; i < listas.getLength(); i++) {
            NamedNodeMap nnm = listas.item(i).getAttributes();
            if (nnm.item(0).getNodeValue().contains("GRUPOS_")) {
                
                grupos.add(listas.item(i));
            }
        }
        
        for (int i = 0; i < grupos.size(); i++) {
            Node nNode = grupos.get(i);
            if(nNode.getNodeType() == Node.ELEMENT_NODE) {
                Element eElement = (Element) nNode;

                System.out.println("CLAVE: "  + eElement.getElementsByTagName("salida").item(0).getTextContent());
                System.out.println("NOMBRE: "  + eElement.getElementsByTagName("salida").item(1).getTextContent());
                System.out.println("CODIGO_CURSO: "  + eElement.getElementsByTagName("salida").item(2).getTextContent());
            }

            
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lst_cursos;
    private javax.swing.JList<String> lst_grupos;
    private javax.swing.JList<String> lst_materias;
    private javax.swing.JMenuItem mn_importar;
    private javax.swing.JMenuItem mn_restore;
    private javax.swing.JMenuItem mn_save;
    // End of variables declaration//GEN-END:variables
}
